### ISSUE TITLE
Так какие же результаты бассейна? о_О

### ISSUE THREAD

**Issue by sky-183** [kukinpower/21_piscine_guide#1]
https://github.com/kukinpower/21_piscine_guide#%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-%D0%B6%D0%B4%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0-%D0%BF%D1%80%D0%BE%D1%88%D1%91%D0%BB-%D0%B8%D0%BB%D0%B8-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D1%88%D1%91%D0%BB-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B1%D0%B0%D1%81%D1%81%D0%B5%D0%B9%D0%BD%D0%B0

`И потом спустя время, что`

Да что же это за клифхенгер такой?)

**Comment by romanwrites** [comment]
😁 
Спасибо, что заметил, по результатам — прошёл. Закоммитил обновление)
